server:
  port: 8081
dubbo:
  application:
    id: apache-2.7-consumer
    name: apache-2.7-consumer
  registry:
    address: zookeeper://43.143.232.133:2181 # 注册中心
  consumer:
    validation: true
    filter: -validation,customValidationFilter
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: dubbo-consumer
