server:
  port: 8081
  servlet:
    context-path: /
dubbo:
  application:
    id: apache-2.7-consumer
    name: apache-2.7-consumer
  registry:
    address: zookeeper://43.143.232.133:2181 # 注册中心
  consumer:
    validation: true
    filter: -validation,customValidationFilter
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  application:
    name: dubbo-consumer
  servlet:
    multipart:
      # 最大支持文件大小
      max-file-size: 4MB
      # 最大支持请求大小
      max-request-size: 4MB
      enabled: true
