server:
  port: 8080
dubbo:
  application:
    name: apache-2.7-provider
    id: apache-2.7-provider
  #    qos-enable: false # 禁用QOS 同一台机器可能会端口冲突
#    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://127.0.0.1:2181 # 注册中心
  protocol:
    name: dubbo # 几种调用方式吧，应该
    port: 20883
  consumer:
    validation: true