server:
  port: 8080
dubbo:
  application:
    name: apache-2.7-provider
    id: apache-2.7-provider
  #    qos-enable: false # 禁用QOS 同一台机器可能会端口冲突
  #    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://43.143.232.133:2181 # 注册中心
  protocol:
    name: dubbo # 几种调用方式吧，应该
    port: 20883
  consumer:
    validation: true
  provider:
    filter: traceFilter
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: cceverfor
    password: 5664c.c.
    url: jdbc:mysql://43.140.221.95:3308/oneforall?characterEncoding=UTF-8&&serverTimezone=GMT&&rewriteBatchedStatements=true # 编码和时区 &userSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 12
      connection-timeout: 60000
      idle-timeout: 50000
      max-lifetime: 55000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 定义枚举类型
    # default-enum-type-handler: