### 1. 字符串
GET http://localhost:8081/say/123
Accept: application/json

### 2. 对象
POST http://localhost:8081/obj
Accept: application/json
Content-Type: application/json

{
  "str": "str",
  "createUserId": "createUserId"
}

### 21. 对象 save和 update 校验
POST http://localhost:8081/saveWithUpdate
Accept: application/json
Content-Type: application/json

{
  "strSave": "strSave",
  "strUpdate": "strUpdate"
}
### "strSave": "strSave",
### "strCommon": "strCommon",
### "strUpdate": "strUpdate",

### 22. 对象 update 校验
POST http://localhost:8081/saveAppendUpdate
Accept: application/json
Content-Type: application/json

{
  "strUpdate": "strUpdate",
  "id": 1
}

### 23. 公共字段 对象 save和 update 和 common 校验
POST http://localhost:8081/strCommon
Accept: application/json
Content-Type: application/json

{
  "strSave": "strSave",
  "strUpdate": "strUpdate",
  "strCommon": "strCommon",
  "id": 1
}

### 404
GET http://localhost:8081/dubbo-consumer/aaaa
Accept: application/json